# Generated by Django 5.0.1 on 2024-07-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=30)),
                ('candidate_mail', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(max_length=15)),
                ('candidate_quali', models.CharField(max_length=40)),
                ('candidate_post', models.CharField(max_length=30)),
                ('condidate_address', models.CharField(max_length=50)),
                ('condidate_cv', models.FileField(upload_to='')),
                ('condidate_message', models.TextField()),
            ],
        ),
    ]
