# Generated by Django 5.0.1 on 2024-06-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='about/'),
        ),
    ]
